name: zemin
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0-362.0.dev

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  latlng: any
  cached_network_image: ^3.2.0
  flutter_localizations:
    sdk: flutter
  platform: ^3.1.0
  map: ^1.4.1
  turf: ^0.0.7
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
